wandb_version: 1

activation:
  value: silu
augment:
  value: true
batch_norm:
  value: true
batch_size:
  value: 128
dense:
  value: 64
dropout:
  value: 0.2
filter_initial:
  value: 16
filter_strategy:
  value: doubled
kernel:
  value:
  - 5
  - 5
  - 5
  - 5
  - 5
learning_rate:
  value: 0.000222173377798958
momentum:
  value: 0.9037190504081948
optimizer:
  value: sgd
resize:
  value: 32
weight_decay:
  value: 0.00562128749228529
