wandb_version: 1

augment:
  value: false
batch_norm:
  value: true
batch_size:
  value: 64
conv_activation:
  value: silu
dense:
  value: 2048
dense_activation:
  value: gelu
dropout:
  value: 0.1
filter_initial:
  value: 32
filter_strategy:
  value: halved
kernel:
  value:
  - 3
  - 3
  - 3
  - 3
  - 3
learning_rate:
  value: 0.00010530909621999338
momentum:
  value: 0.9855523324590392
optimizer:
  value: adamw
resize:
  value: 32
weight_decay:
  value: 0.00015531349463978938
