_wandb:
    value:
        cli_version: 0.19.7
        m: []
        python_version: 3.12.3
        t:
            "1":
                - 1
                - 11
                - 41
                - 49
                - 55
            "2":
                - 1
                - 11
                - 41
                - 49
                - 55
            "3":
                - 16
                - 17
                - 23
                - 55
            "4": 3.12.3
            "5": 0.19.7
            "6": 4.42.3
            "8":
                - 2
                - 5
            "12": 0.19.7
            "13": darwin-x86_64
augment:
    value: false
batch_norm:
    value: false
batch_size:
    value: 32
conv_activation:
    value: relu
dense:
    value:
        - 64
dense_activation:
    value: relu
dropout:
    value: 0
filter_automated:
    value: true
filter_initial:
    value: 32
filter_manual:
    value:
        - 16
        - 32
        - 64
        - 128
        - 256
filter_strategy:
    value: doubled
kernel:
    value:
        - 3
        - 3
        - 3
        - 3
        - 3
learning_rate:
    value: 0.001
momentum:
    value: 0.9
n_convolutions:
    value: 5
n_dense:
    value: 1
optimizer:
    value: adam
padding:
    value: true
resize:
    value: 128
stride:
    value:
        - 1
        - 1
        - 1
        - 1
        - 1
sweep_id:
    value: null
wandb:
    value: true
wandb_entity:
    value: da24d008-iit-madras
wandb_project:
    value: da6401-assignment2
wandb_sweep:
    value: false
weight_decay:
    value: 0
xavier_init:
    value: false
